export function frontToBackReceipt(ruleForm) {
  return {
    TransactionId: ruleForm.TransactionId || null,
    TxType: null,
    MemberId: null,
    MemberName: null,
    DateRequest: ruleForm.DateRequest || null,
    MemberContact: ruleForm.name || null,
    MemberContactPhoneNumber: ruleForm.phone || null,
    ClientId: ruleForm.clientID || null,
    ClientName: ruleForm.clientCompany || null,
    ClientContact: ruleForm.clientName || null,
    ClientContactPhoneNumber: ruleForm.clientPhone || null,
    GoodsListRequested: [{
      VarietyCode: ruleForm.goodsVariety || null,
      Quantity: parseInt(ruleForm.goodsQuantity) || null,
      Quality: ruleForm.goodsLevel || null,
      Brand: ruleForm.goodsBand || null,
      GoodsPackage: ruleForm.goodsPack || null,
      GoodsSpecification: ruleForm.goodsRank || null,
      ProductionPlace: ruleForm.goodsRegion || null,
      ProductionDate: ruleForm.goodsProduceDate || null,
      ValidDate: ruleForm.goodsValidityPeriod || null,
    }],
    ModeOfTransport: ruleForm.goodsTransport || null,
    TargetWarehouseId: ruleForm.warehouseID || null,
    TargetWarehouseName: null,
    DateInplan: ruleForm.inboundPlanTime || null,
    DateCheck: null,
    CheckState: ruleForm.CheckState || null,
    GoodsListPermitted: [],
    DatePermitted: null,
    Description: null,
    GoodsListIndeed: [],
    DateIndeed: null,
    WarehouseReceipts: [],
    DateCreate: null
  }
}

export function backToFrontReceipt(ruleForm) {
  return {
    TransactionId: ruleForm.TransactionId || null,
    TxType: null,
    MemberId: null,
    MemberName: null,
    DateRequest: ruleForm.DateRequest || null,
    name: ruleForm.MemberContact || null,
    phone: ruleForm.MemberContactPhoneNumber || null,
    clientID: ruleForm.ClientId || null,
    clientCompany: ruleForm.ClientName || null,
    clientName: ruleForm.ClientContact || null,
    clientPhone: ruleForm.ClientContactPhoneNumber || null,
    goodsVariety: ruleForm.GoodsListRequested[0].VarietyCode || null,
    goodsQuantity: parseInt(ruleForm.GoodsListRequested[0].Quantity) || null,
    goodsLevel: ruleForm.GoodsListRequested[0].Quality || null,
    goodsBand: ruleForm.GoodsListRequested[0].Brand || null,
    goodsPack: ruleForm.GoodsListRequested[0].GoodsPackage || null,
    goodsRank: ruleForm.GoodsListRequested[0].GoodsSpecification || null,
    goodsRegion: ruleForm.GoodsListRequested[0].ProductionPlace || null,
    goodsProduceDate: ruleForm.GoodsListRequested[0].ProductionDate || null,
    goodsValidityPeriod: ruleForm.GoodsListRequested[0].ValidDate || null,
    goodsTransport: ruleForm.ModeOfTransport || null,
    warehouseID: ruleForm.TargetWarehouseId || null,
    TargetWarehouseName: null,
    inboundPlanTime: ruleForm.DateInPlan || null,
    DateCheck: null,
    CheckState: ruleForm.CheckState || null,
    GoodsListPermitted: [],
    DatePermitted: null,
    Description: null,
    GoodsListIndeed: [],
    DateIndeed: null,
    WarehouseReceipts: [],
    DateCreate: null
  }
}